// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySelfUpdate() {
  return window['go']['main']['App']['ApplySelfUpdate']();
}

export function CheckElvUIUpdate() {
  return window['go']['main']['App']['CheckElvUIUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckSelfUpdate() {
  return window['go']['main']['App']['CheckSelfUpdate']();
}

export function ConfirmInstallAddon() {
  return window['go']['main']['App']['ConfirmInstallAddon']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function InstallElvUIUpdate() {
  return window['go']['main']['App']['InstallElvUIUpdate']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function OpenAddonsFolder() {
  return window['go']['main']['App']['OpenAddonsFolder']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PickAddonsFolder() {
  return window['go']['main']['App']['PickAddonsFolder']();
}

export function SetAutoCheck(arg1) {
  return window['go']['main']['App']['SetAutoCheck'](arg1);
}
