// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplySelfUpdate():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CheckSelfUpdate():Promise<main.SelfUpdateInfo>;

export function GetStatus():Promise<main.AppStatus>;

export function InstallUpdate():Promise<string>;

export function OpenAddonsFolder():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PickAddonsFolder():Promise<string>;

export function SetAutoCheck(arg1:boolean):Promise<void>;
